spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  application:
    name: delivery-tracker
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/notification?currentSchema=notification_schema}
    username: ${DB_USER:abhilash}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: notification_schema
    change-log: classpath:db-changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${DELIVERY_TRACKER_PORT:8003}
  shutdown: graceful

logging:
  level:
    root: INFO
    delivery: DEBUG

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
